apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-myreplicaset
  labels:
    app: myreplicaset
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myreplicaset
  template:
    metadata:
      labels:
        app: myreplicaset
    spec:
      serviceAccountName: {{ .Release.Name }}-myreplicaset
      containers:
      - name: myreplicaset
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}